apiVersion: v1
kind: Secret
metadata:
  name: model-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_TOKEN: {{ .Values.secret.OPENAI_API_TOKEN | quote }}
  OPENAI_API_ENDPOINT: {{ .Values.secret.OPENAI_API_ENDPOINT | quote }}
  OPENAI_MODEL: {{ .Values.secret.OPENAI_MODEL | quote }}
  OPENAI_TEMPERATURE: {{ .Values.secret.OPENAI_TEMPERATURE | quote }}
